language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails_4.2.x.gemfile
  - gemfiles/rails_5.0.x.gemfile
  - gemfiles/rails_5.1.x.gemfile
  - gemfiles/rails_5.2.x.gemfile
  - gemfiles/rails_6.0.x.gemfile
  - gemfiles/rails_master.gemfile

after_success:
  - bundle exec codeclimate-test-reporter

matrix:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails_5.2.x.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_6.0.x.gemfile
    - rvm: 2.3
      gemfile: gemfiles/rails_master.gemfile
cache: bundler
