language: ruby
rvm:
  - 2.3
  - 2.4

install: bundle install

gemfile:
  - gemfiles/4.0.x.gemfile
  - gemfiles/4.1.x.gemfile
  - gemfiles/4.2.x.gemfile
  - gemfiles/5.0.x.gemfile
  - gemfiles/5.1.x.gemfile

matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/4.0.x.gemfile
    - rvm: 2.4
      gemfile: gemfiles/4.1.x.gemfile
