language: ruby
rvm:
  - 2.3
  - 2.4

gemfile:
  - gemfiles/rails_4.0.x.gemfile
  - gemfiles/rails_4.1.x.gemfile
  - gemfiles/rails_4.2.x.gemfile
  - gemfiles/rails_5.0.x.gemfile
  - gemfiles/rails_5.1.x.gemfile
  - gemfiles/rails_master.gemfile

after_success:
  - bundle exec codeclimate-test-reporter

matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails_4.0.x.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_4.1.x.gemfile
  allow_failures:
    - gemfile: gemfiles/rails_master.gemfile

cache: bundler
