language: ruby
rvm:
  - 2.3
  - 2.4

gemfile:
  - gemfiles/rails_4.0.x.gemfile
  - gemfiles/rails_4.1.x.gemfile
  - gemfiles/rails_4.2.x.gemfile
  - gemfiles/rails_5.0.x.gemfile
  - gemfiles/rails_5.1.x.gemfile

matrix:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails_4.0.x.gemfile
    - rvm: 2.4
      gemfile: gemfiles/rails_4.1.x.gemfile
